version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: foobar
      DB_NAME: bankdb

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: foobar
      MYSQL_DATABASE: bankdb
    ports:
      - "3307:3306"  # Use a different host port (e.g., 3307) for MySQL
