version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
