version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql-container  # Replace with the name of your existing MySQL container
      - DB_USER=David  # Replace with your MySQL user
      - DB_PASSWORD=LiloDavo1996#  # Replace with your MySQL password
      - DB_NAME=bankdb  # Replace with your MySQL database name
      - db_redis_host=172.17.0.2  # New line for Redis host
      - db_redis_port=6379              # New line for Redis port
      - db_redis_password=LiloDavo1996# # New line for Redis password
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
