# Use the official MySQL image as a parent image
FROM mysql:8

# Set the root password
ENV MYSQL_ROOT_PASSWORD foobar

# Create a database when the container starts
ENV MYSQL_DATABASE bankdb

# Expose the MySQL port
EXPOSE 3306
