version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql-container  # Replace with the actual host or IP of your MySQL server
      - DB_USER=David
      - DB_PASSWORD=LiloDavo1996#
      - DB_NAME=bankdb
      networks:
        mynetwork:

  networks:
    mynetwork:
      ipam:
        config:
          - subnet: 172.20.0.0/16    