version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql-container
      - DB_USER=root
      - DB_PASSWORD=LiloDavo1996#
      - DB_NAME=bankdb
    networks:
      - mynetwork

networks:
  default:
    external:
      name: mynetwork
