version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=foobar
      - DB_NAME=bankdb
    networks:
      - my-network

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
    networks:
      my-network:
        ipv4_address: 172.26.0.2
      my-network-alias:
        aliases:
          - mysql-db
    command: --bind-address=0.0.0.0

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16

