# Dockerfile.mysql

# Use the official MySQL image as a parent image
FROM mysql:8

# Set the root password
ENV MYSQL_ROOT_PASSWORD foobar

# Copy the initialization script into the container
COPY init.sql /docker-entrypoint-initdb.d/