version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=foobar
      - DB_NAME=bankdb
    networks:
      - my-network

  mysql-db:
    image: mysql:3
    environment:
      - MYSQL_ROOT_PASSWORD=foobar
    networks:
      - my-network
    ip: 172.20.0.2  # Use 'ip' instead of 'ipv4_address'
    command: --bind-address=0.0.0.0

networks:
  my-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
