version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-container
    environment:
      - DB_HOST=mysql-container
      - DB_USER=David
      - DB_PASSWORD=LiloDavo1996#
      - DB_NAME=bankdb
    networks:
      - mynetwork

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - mynetwork
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "LiloDavo1996#"
      MYSQL_DATABASE: "bankdb"
      MYSQL_USER: "David"
      MYSQL_PASSWORD: "LiloDavo1996#"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "0.0.0.0:3307:3306"
    ip: "172.20.0.2"

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
