version: '3'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=David
      - DB_PASSWORD=LiloDavo1996#
      - DB_NAME=bankdb
    networks:
      my-network:

  mysql-db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=LiloDavo1996#
    networks:
      my-network:
        ipv4_address: 172.20.0.2  # Assign a static IP address
    command: --bind-address=0.0.0.0

networks:
  my-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
